### PR TITLE
Bug fix

### LINKED ISSUE #87: Remove null Patient in Room Class
Reducing the existence of null, improves code quality.

### LINKED ISSUE #150: InitRoom bug
InitRoom allows user to reduce the number of rooms disregarding the case where some of the patients can be left stranded when number of rooms are reduced.

### PR DESCRIPTION
**Pull request by itssodium**
Below are the bugs that I fixed:

change initRoom such that you can only decrease number of rooms if the reduced number of rooms can accommodate the existing the number of Patients, else error is thrown
Also add additional layer of abstraction of UniquePatientList and its respective test cases
Also JsonRoomOccupancyStorage implements RoomRecordsStorage

### CODE REVIEW

File: src/main/java/seedu/address/model/ModelManager.java [hunk 1]
```diff
@@ -200,13 +213,6 @@ public void setSingleRoom(Room target, Room editedRoom) {
     }
     //@@author LeeMingDe
 
-    @Override
-    public Optional<Room> getRoomWithRoomNumber(int roomNumber) {
-        assert (roomNumber > 0) : "Room number should be greater than 0.";
-        return roomList.getRoomWithRoomNumber(roomNumber);
-    }
-
-    //@@author chiamyunqing
```
Comment (chiamyunqing) [inline src/main/java/seedu/address/model/ModelManager.java:209]: I think this line should be added back cos it's meant for the next function removePatientFromRoom()

File: src/main/java/seedu/address/model/ModelManager.java [hunk 2]
```diff
@@ -250,6 +256,14 @@ public void updateRoomListWhenPatientsChanges(Patient patientToEdit, Patient edi
     }
     //@@author LeeMingDe
 
+    @Override
+    public Optional<Room> getRoomWithRoomNumber(int roomNumber) {
+        assert (roomNumber > 0) : "Room number should be greater than 0.";
+        return roomList.getRoomWithRoomNumber(roomNumber);
+    }
+
+    //@@author chiamyunqing
```
Comment (chiamyunqing) [inline src/main/java/seedu/address/model/ModelManager.java:265]: and this line should be removed.

File: src/main/java/seedu/address/model/UniqueRoomList.java [hunk 3]
```diff
@@ -0,0 +1,355 @@
...
+            for (int i = numOfRooms; i < size; i++) {
+                internalList.remove(numOfRooms);
+            }
+        }
+    }
+
+    /**
+     * Gives list of empty rooms in the region which exists after shrinkage.
+     */
+    public List<Room> unOccupiedRooms() {
```
Comment (chiamyunqing) [inline src/main/java/seedu/address/model/UniqueRoomList.java:140]: Mmm just wondering what this function and occupiedRooms() function is for? Do we need to know the list of empty and occupied rooms? Unless it's to find the first unoccupied room which I think your priority queue will have been able to find?

File: src/main/java/seedu/address/model/room/Room.java [hunk 4]
```diff
@@ -150,25 +174,29 @@ public boolean equals(Object o) {
...
                     && roomNumber == room.roomNumber
                     && isOccupied == room.isOccupied;
         } else if (taskList == null) {
             return roomNumber == room.roomNumber
                     && room.taskList == null
                     && isOccupied == room.isOccupied
                     && patient.equals(room.getPatient());
-        } else if (patient == null) {
+        } else if (patient.isEmpty()) {
+            System.out.println(roomNumber == room.roomNumber
```
Comment (chiamyunqing) [inline src/main/java/seedu/address/model/room/Room.java]: Can remove this System.out.println()

File: src/test/data/JsonSerializableRoomListTest/typicalRoomsInRoomList.json [hunk 5]
```diff
@@ -1,20 +1,62 @@
 {
-  "rooms" : [ {
```
Comment (chiamyunqing) [inline src/test/data/JsonSerializableRoomListTest/typicalRoomsInRoomList.json:2]: I think you may need to change this json file back to the original one since this json file should follow the rooms set in getTypicalRoom() from the TypicalRooms class. The getTypicalRoom() function is being used by other test cases for task and patient commands which heavily depends on the order in the room list so I am not sure if changing this file will propagate errors to those test cases for tasks and patients. :/

File: src/test/java/seedu/address/logic/commands/room/AllocateRoomCommandTest.java [hunk 6]
```diff
@@ -28,6 +23,7 @@
 /**
  * Contains integration tests and unit tests for AllocateRoomCommand.
  */
+//TODO: Please clean up test cases for this method, seems weird to have only rooms 7-10 in a hotel facility.
```
Comment (chiamyunqing) [inline src/test/java/seedu/address/logic/commands/room/AllocateRoomCommandTest.java:26]: I think it's fine to have so few rooms in the test cases since we are just testing that the functions work as expected rather than testing if the app works on a large scale. What do you think?

File: src/test/java/seedu/address/storage/JsonSerializableRoomListTest.java [hunk 7]
```diff
@@ -21,6 +21,8 @@ public void toModelType_typicalRoomFile_success() throws Exception {
                 JsonSerializableRoomList.class).get();
         RoomList covigentAppFromFile = dataFromFile.toModelType();
         RoomList typicalRoomList = TypicalRooms.getTypicalRoomList();
+        System.out.println(covigentAppFromFile.getRoomObservableList());
```
Comment (chiamyunqing) [inline src/test/java/seedu/address/storage/JsonSerializableRoomListTest.java]: Remove the System.out.println?

**Review by chiamyunqing — DISMISSED** [review]
Good job in abstracting out the UniqueRoomList! Just some things to take note of. While you are right that it does not make sense for a hotel to have so few rooms, I think the main thing is more on testing whether the functions work as expected rather than whether the app works on a large scale in those test cases. I am not sure if changing the Json file test input will propagate to errors in some task and patient command test cases because they rely on the the getTypicalRooms() function which must be in that order also. Maybe you might want to look into that?

File: src/main/java/seedu/address/model/UniqueRoomList.java [hunk 8]
```diff
@@ -0,0 +1,355 @@
...
+    public int numOfOccupiedRooms() {
+        return (int) IntStream.rangeClosed(numOfRooms, internalList.size() - 1)
+                .mapToObj(x -> internalList.get(x)).filter(Room::isOccupied).count();
+    }
+
+    /**
+     * Gives the number of rooms that are empty for room numbers after shrinkage.
+     */
+    public int numOfEmptyRooms() {
+        return (int) IntStream.rangeClosed(0, numOfRooms - 1)
```
Comment (w-yeehong) [inline src/main/java/seedu/address/model/UniqueRoomList.java:194]: Is it necessary to cast to `(int)` here. `count()` should return an `int` I think.

File: src/main/java/seedu/address/logic/commands/room/InitRoomCommand.java [hunk 9]
```diff
@@ -31,10 +33,13 @@ public InitRoomCommand(int numOfRooms) {
     }
     @Override
     public CommandResult execute(Model model) throws CommandException {
+        model.setInitNumOfRooms(numOfRooms);
         if (numOfRooms == 0) {
             throw new CommandException(MESSAGE_ZERO_CANNOT_BE_AN_INPUT);
         } else if (numOfRooms < 0) {
             throw new CommandException(MESSAGE_NEGATIVE_VALUES_CANNOT_BE_INPUT);
+        } else if (model.getNumOfRooms() > numOfRooms && !model.canFit()) {
```
Comment (w-yeehong) [inline src/main/java/seedu/address/logic/commands/room/InitRoomCommand.java]: Hmm I think maybe `model.canFit()` can be renamed? It is difficult to understand what that method does. Perhaps `hasSpaceForRooms()`? Same for the other `canFit()` methods.

File: src/main/java/seedu/address/model/ModelManager.java (hunk 2 above)
Comment (itssodium) [reply src/main/java/seedu/address/model/ModelManager.java:265]: Same function?

File: src/main/java/seedu/address/model/RoomList.java [hunk 10]
```diff
@@ -44,82 +46,60 @@ public RoomList(ReadOnlyRoomList readOnlyRoomList) {
...
-            for (int i = numOfRooms; i < size; i++) {
-                internalList.remove(numOfRooms);
-            }
-        }
-        internalList.setAll(rooms); // to let the UI update
+    public ObservableList<Room> getRoomObservableList() {
+        return rooms.getRoomObservableList();
     }
 
+    public void setData(Room room) {
```
Comment (w-yeehong) [inline src/main/java/seedu/address/model/RoomList.java]: Do you think `setRoom()` would be clearer here?

File: src/main/java/seedu/address/model/RoomList.java [hunk 11]
```diff
@@ -28,13 +24,19 @@
 public class RoomList implements ReadOnlyRoomList {
```
Comment (w-yeehong) [inline src/main/java/seedu/address/model/RoomList.java:25]: Would you like to rename this to `RoomRecords` to keep it consistent with `PatientRecords`?

**Review by w-yeehong — APPROVED** [review]
Thank you for abstracting `RoomList` into two classes and making `Patient` optional in `Room`. Do address @chiamyunqing's comments and I think you're good to go 👍

File: src/main/java/seedu/address/logic/commands/room/InitRoomCommand.java (hunk 9 above)
Comment (itssodium) [reply src/main/java/seedu/address/logic/commands/room/InitRoomCommand.java]: Okay

File: src/main/java/seedu/address/model/Model.java [hunk 12]
```diff
@@ -125,6 +126,9 @@
 
     void addRooms(int num);
 
+    boolean canFit();
```
Comment (LeeMingDe) [inline src/main/java/seedu/address/model/Model.java]: will it be possible to add in java docs for these methods?

File: src/main/java/seedu/address/model/RoomList.java (hunk 10 above)
Comment (LeeMingDe) [reply src/main/java/seedu/address/model/RoomList.java]: i think there's already a method called setRoom()

File: src/main/java/seedu/address/model/RoomList.java (hunk 11 above)
Comment (itssodium) [reply src/main/java/seedu/address/model/RoomList.java:25]: A little weird to be RoomRecords since it is a list of rooms

File: src/main/java/seedu/address/model/room/Room.java [hunk 13]
```diff
@@ -150,25 +174,29 @@ public boolean equals(Object o) {
         }
 
         Room room = (Room) o;
-        if (taskList == null && patient == null) {
+        if (taskList == null && patient.isEmpty()) {
```
Comment (LeeMingDe) [inline src/main/java/seedu/address/model/room/Room.java]: maybe can check if taskList.isEmpty();

File: src/test/java/seedu/address/logic/commands/room/AllocateRoomCommandTest.java (hunk 6 above)
Comment (LeeMingDe) [reply src/test/java/seedu/address/logic/commands/room/AllocateRoomCommandTest.java:26]: yup, i think it should be fine since you are doing unit testing to ensure that the function works

**Review by LeeMingDe — APPROVED** [review]
lgtm!

File: src/main/java/seedu/address/model/room/Room.java (hunk 13 above)
Comment (itssodium) [reply src/main/java/seedu/address/model/room/Room.java]: yes, good point.

File: src/main/java/seedu/address/model/Model.java (hunk 12 above)
Comment (itssodium) [reply src/main/java/seedu/address/model/Model.java]: Okay.
