### PR TITLE
Fix task index not updating in search results

### LINKED ISSUE #226: Task index does not update when adding or deleting tasks not in search results
### Details 

When searching for results, a `FilteredList` is used. Adding new tasks or deleting tasks not in the search results do not cause the UI  to refresh.

### Steps to reproduce:
1. Execute `initroom 5`.
1. Execute `addtask r/1 d/Hello World dd/20201230`
1. Proceed to the Task tab.
1. Execute `searchtask dd/20201231`
1. Execute `addtask r/1 d/World Hello`
1. Notice that the Task tab still displays `Task 1 of 1` instead of `Task 1 of 2`.

### PR DESCRIPTION
**Pull request by w-yeehong**
Let's add a listener on the original `ObservableList` of the tasks in a room to monitor for changes. This allows the task indexes to be updated upon adding or deleting a task not found within the search results.

### CODE REVIEW

File: src/main/java/seedu/address/ui/RoomTaskDetailsPanel.java [hunk 1]
```diff
@@ -67,6 +75,30 @@ private void setCellSize(ObservableList<Task> taskList) {
...
+     * @param roomTaskList The task list to listen to for changes.
+     */
+    private void updateDetailsIfChanged(ObservableList<Task> roomTaskList) {
+        roomTaskList.addListener(new ListChangeListener<Task>() {
+            @Override
+            public void onChanged(Change<? extends Task> change) {
+                while (change.next()) {
+                    int indexOfChange = change.getFrom();
+                    Index index = Index.fromZeroBased(indexOfChange);
+                    logger.info("Changes detected in Task " + index.getOneBased()
```
Comment (chiamyunqing) [inline src/main/java/seedu/address/ui/RoomTaskDetailsPanel.java:94]: Good use of logger here.

**Review by chiamyunqing — APPROVED** [review]
LGTM.
