### PR TITLE
Bug fix noorul ped

### LINKED ISSUE #160: [PE-D] Application Hangs
Application hangs for several minutes when too many rooms are initialized at once. Maybe can set a limit to the number of rooms that can be initialized at one go!

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: yanlynnnnn/ped#4

### LINKED ISSUE #175: [PE-D] initroom error when declaring less rooms than patients
When there are 17 patients, and I add 4 rooms, it is allowed even though the UG said should be an error. 

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: KishenKumarrrrr/ped#11

### LINKED ISSUE #177: [PE-D] Extra parameters allowed in listroom.
listroom r/1111111 allows me to still list rooms even tho I am passing in extra parameters. 

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: KishenKumarrrrr/ped#13

### LINKED ISSUE #186: [PE-D] Can initalise one room even though there is more than one patient
Actually I'm not sure what 'If the number of rooms is less than the number of patients error is thrown when decreasing the number of existing rooms.'(taken from your user guide) means. Is there supposed to be an error thrown when the user inputs 'initroom 1' for the first time and there is more than one patient? Currently it will not throw an error message, 'initroom 10' followed by 'initroom 1' will not throw an error message either. 

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: yuxuanxc/ped#4

### LINKED ISSUE #191: [PE-D] Wrong error message for initroom
Should be initroom 200

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: yingqi0607/ped#4

### LINKED ISSUE #192: [PE-D] UG FAQ section
The last QnA, should be `java -jar covigent.jar`.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: yingqi0607/ped#5

### LINKED ISSUE #199: [PE-D] initroom clears all the previous created rooms
while initroom is meant to initialise the rooms for the first time, however, when i want to add in more rooms or modify the room numbers, there is no way to do this, initroom will simply clears all the previous room data. The team may consider add in the relevant commands for such purposes that may be needed in the real world. Also might need a field to store the address of the room instead of simply a room number.  

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: DreamerDragon/ped#7

### LINKED ISSUE #206: [PE-D] Inconsistencies in the naming of the 'findemptyroom' command in UG
In the TOC, the command to find the first free room is 'findroom', but in the features section, it is 'findemptyroom'. 

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: cheoksuanne/ped#1

### PR DESCRIPTION
**Pull request by itssodium**
BugFix according to that stated in PED

- make initroom faster
- make minor changes to UG to make it more consistent
- make changes to UG to make it clearer
- changed the error thrown by InitRoomCommandParser
- make changes to JsonSerializableRoomList so that it only takes in ordered rooms

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/room/InitRoomCommand.java [hunk 1]
```diff
@@ -16,6 +16,8 @@
     public static final String MESSAGE_ZERO_CANNOT_BE_AN_INPUT = "Please input a positive value";
     public static final String MESSAGE_NEGATIVE_VALUES_CANNOT_BE_INPUT = "Please check your value! "
             + "You have input a negative value!";
+    public static final String MESSAGE_LARGE_NUMBER_OF_ROOMS_INPUT = "Please reduce the number of rooms input."
+            + "maximum number of rooms are 5000";
```
Comment (raymondge) [inline src/main/java/seedu/address/logic/commands/room/InitRoomCommand.java:20]: maximum number...is 5000, just small gramma

File: src/main/java/seedu/address/storage/JsonSerializableRoomList.java [hunk 2]
```diff
@@ -17,6 +17,7 @@
 @JsonRootName(value = "roomList")
 public class JsonSerializableRoomList {
 
+    public static final String WRONG_ORDER_OF_ROOM = "Rooms are not inserted in the correct order.";
```
Comment (raymondge) [inline src/main/java/seedu/address/storage/JsonSerializableRoomList.java]: maybe you want to change the word "inserted"?

**Review by raymondge — APPROVED** [review]
LGTM

File: src/main/java/seedu/address/commons/core/Messages.java [hunk 3]
```diff
@@ -21,12 +21,13 @@
 
     public static final String MESSAGE_INVALID_ROOM_NUMBER = "The room number provided "
             + "cannot be found in Covigent.";
-    public static final String NUMBER_OF_ROOMS_GIVEN_IN_DIGITS = "Please give the number of digits in numbers\n"
+    public static final String NUMBER_OF_ROOMS_GIVEN_IN_DIGITS = "Please give the number of digits in integers\n"
             + "Example: addRooms 200";
```
Comment (chiamyunqing) [inline src/main/java/seedu/address/commons/core/Messages.java]: I think the command is "initroom" and not "addRooms" anymore?

File: src/main/java/seedu/address/commons/core/Messages.java [hunk 4]
```diff
@@ -21,12 +21,13 @@
...
     public static final String MESSAGE_PATIENT_ALREADY_ASSIGNED = "Patient has already been assigned a room.\nPlease"
             + " clear patient from the room first.";
     public static final String MESSAGE_PATIENT_NO_ROOM = "Patient is not assigned to any room yet.";
-
+    public static final String MESSAGE_NO_EXCESS_WORDS_LIST_ROOM = "No excess words for list room.";
```
Comment (chiamyunqing) [inline src/main/java/seedu/address/commons/core/Messages.java]: Do we still need this for listroom since our implementation for listroom and listpatient ignores the excess words?

File: src/main/java/seedu/address/logic/commands/room/InitRoomCommand.java (hunk 1 above)
Comment (chiamyunqing) [reply src/main/java/seedu/address/logic/commands/room/InitRoomCommand.java:20]: I was thinking if we should reduce the maximum number of rooms further since our target audience is small boutique hotels?

File: src/main/java/seedu/address/model/room/UniqueRoomList.java [hunk 5]
```diff
@@ -49,13 +49,13 @@ public void setRoom(Room room) {
                 internalList.add(roomToAdd);
                 rooms.add(room);
             }
-            rooms.add(room);
-            internalList.add(room);
+            //rooms.add(room);
```
Comment (chiamyunqing) [inline src/main/java/seedu/address/model/room/UniqueRoomList.java]: Not sure if you still need these 2 lines of code since you commented out, but if you don't need it anymore, don't forget to delete it!

File: src/main/java/seedu/address/commons/core/Messages.java [hunk 6]
```diff
@@ -21,8 +21,8 @@
 
     public static final String MESSAGE_INVALID_ROOM_NUMBER = "The room number provided "
             + "cannot be found in Covigent.";
-    public static final String NUMBER_OF_ROOMS_GIVEN_IN_DIGITS = "Please give the number of digits in numbers\n"
-            + "Example: addRooms 200";
+    public static final String NUMBER_OF_ROOMS_GIVEN_IN_DIGITS = "Please give the number of digits in integers\n"
```
Comment (w-yeehong) [inline src/main/java/seedu/address/commons/core/Messages.java]: Do you think it would be cleaner if we kept this error message in `InitRoomCommandParser` since it is specific to the command?

File: src/main/java/seedu/address/model/RoomList.java [hunk 7]
```diff
@@ -169,8 +169,8 @@ public int hashCode() {
         return rooms.hashCode();
     }
 
-    public void setNumOfRooms(int numOfRooms) {
-        rooms.setNumOfRooms(numOfRooms);
+    public void setPreferredNamOfRooms(int numOfRooms) {
```
Comment (w-yeehong) [inline src/main/java/seedu/address/model/RoomList.java]: I think the method name can be the same here? `setPreferredNumOfRooms` seems okay to me.

File: src/main/java/seedu/address/model/room/UniqueRoomList.java [hunk 8]
```diff
@@ -49,13 +49,11 @@ public void setRoom(Room room) {
...
                 rooms.add(room);
             }
-            rooms.add(room);
-            internalList.add(room);
         } else {
             Room currRoom = internalList.get(roomNumber - 1);
             internalList.remove(roomNumber - 1);
             rooms.remove(currRoom);
-            internalList.add(roomNumber, room);
+            internalList.add(roomNumber - 1, room);
```
Comment (w-yeehong) [inline src/main/java/seedu/address/model/room/UniqueRoomList.java]: Maybe it would be possible to use the `Index` class here. Create an `Index` object from `roomNumber` and use it for the list operations.

This avoids "magic numbers", i.e. the `-1` does not keep appearing.

File: src/main/java/seedu/address/logic/commands/room/InitRoomCommand.java [hunk 9]
```diff
@@ -39,8 +41,10 @@ public CommandResult execute(Model model) throws CommandException {
             throw new CommandException(MESSAGE_ZERO_CANNOT_BE_AN_INPUT);
         } else if (numOfRooms < 0) {
             throw new CommandException(MESSAGE_NEGATIVE_VALUES_CANNOT_BE_INPUT);
+        } else if (numOfRooms > 5000) {
```
Comment (w-yeehong) [inline src/main/java/seedu/address/logic/commands/room/InitRoomCommand.java]: Would be good to define `5000` as a constant `MAX_NUM_OF_ROOM`!

File: src/test/java/seedu/address/logic/commands/room/InitRoomCommandTest.java [hunk 10]
```diff
@@ -105,5 +108,13 @@ void execute_decreaseNumberOfOccupiedRooms_failure() {
                 expectedMessage);
     }
 
+    @Test
+    void execute_largeNumberOfRooms_failure() {
```
Comment (w-yeehong) [inline src/test/java/seedu/address/logic/commands/room/InitRoomCommandTest.java:112]: Good negative test case!

File: src/main/java/seedu/address/model/ModelManager.java [hunk 11]
```diff
@@ -173,8 +174,8 @@ public void updateFilteredPatientList(Predicate<Patient> predicate) {
     //=========== Room List ========================================================================================
 
     @Override
-    public int numOfOccupiedRooms() {
-        return roomList.numOfOccupiedRooms();
+    public int numOfExcessOccupiedRooms() {
```
Comment (w-yeehong) [inline src/main/java/seedu/address/model/ModelManager.java]: We may want to use verbs for the name of methods to make it clearer? `getNumOfOccupiedRooms()`?

May also want to make the Javadocs for this method clearer.

File: src/test/java/seedu/address/logic/commands/room/InitRoomCommandTest.java [hunk 12]
```diff
@@ -69,9 +70,10 @@ void execute_decreaseNumberOfRooms_success() {
     @Test
     void execute_increaseNumberOfOccupiedRooms_success() {
         RoomList roomList = TypicalRooms.getTypicalRoomList();
+        RoomList roomList1 = TypicalRooms.getTypicalRoomList();
+
         Model model = new ModelManager(new PatientRecords(), roomList, new UserPrefs());
-        Model expectedModel =
-                new ModelManager(model.getPatientRecords(), roomList, new UserPrefs());
+        Model expectedModel = new ModelManager(model.getPatientRecords(), roomList1, new UserPrefs());
```
Comment (w-yeehong) [inline src/test/java/seedu/address/logic/commands/room/InitRoomCommandTest.java]: I think you can use rename `roomList1` to `expectedRoomList` to highlight the difference between the 2 `RoomList`. Same for the other test cases!

**Review by w-yeehong — APPROVED** [review]
Good job with adding more test cases! LGTM.

File: src/test/java/seedu/address/logic/commands/room/InitRoomCommandTest.java (hunk 12 above)
Comment (itssodium) [reply src/test/java/seedu/address/logic/commands/room/InitRoomCommandTest.java]: Okay thanks

File: src/main/java/seedu/address/logic/commands/room/InitRoomCommand.java (hunk 9 above)
Comment (itssodium) [reply src/main/java/seedu/address/logic/commands/room/InitRoomCommand.java]: Okay thanks.

File: src/main/java/seedu/address/commons/core/Messages.java (hunk 6 above)
Comment (itssodium) [reply src/main/java/seedu/address/commons/core/Messages.java]: Alright.

File: src/main/java/seedu/address/model/RoomList.java (hunk 7 above)
Comment (itssodium) [reply src/main/java/seedu/address/model/RoomList.java]: Typo, sorry.
