### PR TITLE
Fix bug where task commands work with room index instead of room numbers

### LINKED ISSUE #102: Task commands use index of room instead of room number
Currently, `addtask`, `edittask`, and `deletetask` treat the room index in `RoomList` as room numbers. This leads to a bug where task operations fail when the room number has changed through the use of `editroom`.

### PR DESCRIPTION
**Pull request by w-yeehong**
`addtask`, `deletetask`, and `edittask` now work with room number instead of index.

### CODE REVIEW

File: src/main/java/seedu/address/commons/core/Messages.java [hunk 1]
```diff
@@ -13,14 +13,14 @@
...
     // patients
 
-    public static final String MESSAGE_INVALID_PATIENT_NAME_INPUT = "The patient name provided "
+    public static final String MESSAGE_INVALID_PATIENT_NAME = "The patient name provided "
             + "cannot be found in Covigent.";
     public static final String MESSAGE_PATIENT_LISTED_OVERVIEW = "%1$d patient listed!";
 
     // rooms
 
-    public static final String MESSAGE_INVALID_ROOM_NOT_FOUND = "The room number provided is not found.";
```
Comment (chiamyunqing) [inline src/main/java/seedu/address/commons/core/Messages.java:22]: Thanks for removing the duplicated messages!

File: src/main/java/seedu/address/logic/commands/task/AddTaskCommand.java [hunk 2]
```diff
@@ -37,38 +35,41 @@
...
     }
 
     @Override
     public CommandResult execute(Model model) throws CommandException {
         requireNonNull(model);
-        List<Room> rooms = model.getRoomList();
-
-        if (roomIndex.getZeroBased() >= rooms.size()) {
-            throw new CommandException(Messages.MESSAGE_INVALID_ROOM_INDEX);
+        if (roomNumber < 0) {
```
Comment (chiamyunqing) [inline src/main/java/seedu/address/logic/commands/task/AddTaskCommand.java:54]: Actually now I'm wondering if you do your assertion early on in the constructor, then the app will directly crash and will never reach here :X

File: src/main/java/seedu/address/logic/commands/task/DeleteTaskCommand.java [hunk 3]
```diff
@@ -37,49 +35,49 @@
...
+        assert roomNumber > 0 : "Room number should be greater than 0.";
+        this.roomNumber = roomNumber;
         this.taskIndex = taskIndex;
-        this.roomIndex = roomIndex;
     }
 
     @Override
     public CommandResult execute(Model model) throws CommandException {
         requireNonNull(model);
+        if (roomNumber < 0) {
```
Comment (chiamyunqing) [inline src/main/java/seedu/address/logic/commands/task/DeleteTaskCommand.java:55]: Same issue, if you assert in constructor, will this Message Invalid room number be received by user?

File: src/main/java/seedu/address/logic/commands/task/DeleteTaskCommand.java [hunk 4]
```diff
@@ -37,49 +35,49 @@
...
         // Get the task which the user wants to delete
-        List<Task> tasks = targetRoom.getTaskList().asUnmodifiableObservableList();
-        if (taskIndex.getZeroBased() >= tasks.size()) {
-            throw new CommandException(Messages.MESSAGE_INVALID_TASK_INDEX);
-        }
-        Task taskToDelete = tasks.get(taskIndex.getZeroBased());
+        Optional<Task> optionalTask = model.getTaskFromRoomWithTaskIndex(taskIndex, room);
+        Task taskToDelete = optionalTask.orElseThrow(() ->
+                new CommandException(Messages.MESSAGE_INVALID_TASK_INDEX));
         assert taskToDelete != null : "The task to delete should never be null.";
```
Comment (chiamyunqing) [inline src/main/java/seedu/address/logic/commands/task/DeleteTaskCommand.java:69]: If the task to delete is null, the app will just crash?

File: src/main/java/seedu/address/model/ModelManager.java [hunk 5]
```diff
@@ -178,10 +179,16 @@ public void addRooms(int num) {
...
     @Override
     public boolean hasRoom(Room room) {
-        requireAllNonNull(room);
+        requireNonNull(room);
         return roomList.containsRoom(room);
     }
 
+    @Override
+    public Optional<Room> getRoomWithRoomNumber(int roomNumber) {
+        assert (roomNumber > 0) : "Room number should be greater than 0.";
```
Comment (chiamyunqing) [inline src/main/java/seedu/address/model/ModelManager.java:193]: Will this crash the app?

**Review by chiamyunqing — APPROVED** [review]
Good job and thank you for refactoring the messages! Can see that you tried to add some assertions in your code. However, if I am not mistaken, some of your assertions are used in cases when user input is invalid. In such cases, I am not sure if assertions are appropriate since assertions cause the application to crash. (Imagine keying in a room number of -5 and the app crashes ><)

File: src/main/java/seedu/address/logic/commands/task/AddTaskCommand.java [hunk 6]
```diff
@@ -37,38 +35,41 @@
...
     /**
      * Creates an AddTaskCommand to add the specified {@code Task} to a {@code Room}
-     * with the {@code roomIndex}.
+     * with the {@code roomNumber}.
      */
-    public AddTaskCommand(Task task, Index roomIndex) {
-        requireAllNonNull(task, roomIndex);
+    public AddTaskCommand(Task task, int roomNumber) {
+        requireNonNull(task);
+        assert roomNumber > 0 : "Room number should be greater than 0.";
```
Comment (LeeMingDe) [inline src/main/java/seedu/address/logic/commands/task/AddTaskCommand.java:46]: i think you should be asserting if the `roomNumber` is `null`? Because if the roomNumber is <0 then it should be the user fault and not the system fault no?

File: src/main/java/seedu/address/logic/commands/task/EditTaskCommand.java [hunk 7]
```diff
@@ -47,53 +46,49 @@
...
      * Creates an EditTaskCommand to replace a {@code Task} in a {@code Room} with another
      * {@code Task} described by {@code editTaskDescriptor}.
      */
-    public EditTaskCommand(Index roomIndex, Index taskIndex, EditTaskDescriptor editTaskDescriptor) {
-        requireAllNonNull(roomIndex, taskIndex, editTaskDescriptor);
-
-        this.roomIndex = roomIndex;
+    public EditTaskCommand(int roomNumber, Index taskIndex, EditTaskDescriptor editTaskDescriptor) {
+        requireAllNonNull(taskIndex, editTaskDescriptor);
+        assert roomNumber > 0 : "Room number should be greater than 0.";
```
Comment (LeeMingDe) [inline src/main/java/seedu/address/logic/commands/task/EditTaskCommand.java:59]: same here for what yq and i mentioned previously

**Review by LeeMingDe — APPROVED** [review]
lgtm! However, do read the comments about the assertions!

File: src/main/java/seedu/address/logic/commands/task/AddTaskCommand.java (hunk 6 above)
Comment (w-yeehong) [reply src/main/java/seedu/address/logic/commands/task/AddTaskCommand.java:46]: `roomNumber` cannot actually be `null` though, because it is a primitive (i.e. `int`).

File: src/main/java/seedu/address/logic/commands/task/AddTaskCommand.java (hunk 2 above)
Comment (w-yeehong) [reply src/main/java/seedu/address/logic/commands/task/AddTaskCommand.java:54]: Yup that's true. Good observation here 😄

That said, assertions may not necessarily be enabled, especially when an application goes into production.

The `roomNumber < 0` check is to prevent the application from crashing if this method somehow gets called when assertions are off.

File: src/main/java/seedu/address/logic/commands/task/DeleteTaskCommand.java (hunk 4 above)
Comment (w-yeehong) [reply src/main/java/seedu/address/logic/commands/task/DeleteTaskCommand.java:69]: Yup, I think the app is meant to crash in that case. `model.getTaskFromRoomWithTaskIndex(taskIndex, room)` should return either an empty `Optional` or an `Optional`-wrapped task. It should never be `null` here.

The app will crash with a `NullPointerException` if `taskToDelete` is `null` either way.

File: src/main/java/seedu/address/model/ModelManager.java (hunk 5 above)
Comment (w-yeehong) [reply src/main/java/seedu/address/model/ModelManager.java:193]: Yup, it will crash the app provided assertions are enabled. If `getRoomWithRoomNumber(...)` is called with a `roomNumber` greater than 0, it would be a programming error. Crashing in that case is helpful for debugging.
